[phases.setup]
aptPkgs = [
  'build-essential',
  'pkg-config',
  'fonts-liberation',
  'libasound2t64',
  'libatk-bridge2.0-0',
  'libatk1.0-0',
  'libcairo2-dev',
  'libgbm1',
  'libgdk-pixbuf2.0-0',
  'libgif-dev',
  'libglib2.0-0',
  'libgtk-3-0',
  'libjpeg-dev',
  'libnspr4',
  'libnss3',
  'libpango1.0-dev',
  'librsvg2-dev',
  'libx11-xcb1',
  'libxcomposite1',
  'libxcursor1',
  'libxdamage1',
  'libxfixes3',
  'libxi6',
  'libxrandr2',
  'libxss1',
  'libxtst6',
]
